kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "hostname"
spec:
  replicas: 1
  selector:
    name: "hostname"
  template:
    spec:
      containers:
        - name: "hostname-frontend"
          image: "inkysea/go-scale:latest"
          ports:
            - containerPort: 8000
    metadata:
      labels:
        name: "hostname"
  labels:
    name: "hostname"
